-- --------------------------------------------------------

-- SUPPRESSION DES TABLES EXISTANTES
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TYPE_USER;
DROP TABLE IF EXISTS PONTS;
DROP TABLE IF EXISTS STATUS;
DROP TABLE IF EXISTS BATEAUX;
DROP TABLE IF EXISTS CAPTEURS;
DROP TABLE IF EXISTS DIRECTION_CRENEAU;
DROP TABLE IF EXISTS PERIODE_CRENEAU;
DROP TABLE IF EXISTS MESURES_CAPTEURS;

-- --------------------------------------------------------

-- CREATION DE LA TABLE DIRECTION_CRENEAU
CREATE TABLE DIRECTION_CRENEAU (
    DIRECTION_CRENEAU_ID INT NOT NULL AUTO_INCREMENT,
    LIBELLE_DIRECTION_CRENEAU VARCHAR(15),
    PRIMARY KEY (DIRECTION_CRENEAU_ID)
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE CAPTEURS
CREATE TABLE CAPTEURS (
    CAPTEUR_ID INT NOT NULL AUTO_INCREMENT,
    TYPE_CAPTEUR ENUM('temperature', 'turbinite', 'profondeur', 'humidite'),
    LIBELLE_CAPTEUR VARCHAR(50),
    UNITE_MESURE VARCHAR(10),
    EMPLACEMENT VARCHAR(100),
    STATUS ENUM('actif', 'inactif', 'maintenance') DEFAULT 'actif',
    DATE_INSTALLATION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CAPTEUR_ID)
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE PERIODE_CRENEAU
CREATE TABLE PERIODE_CRENEAU (
    PERIODE_ID INT NOT NULL AUTO_INCREMENT,
    LIBELLE_PERIODE VARCHAR(20),
    PRIMARY KEY (PERIODE_ID)
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE PONTS
CREATE TABLE PONTS (
    PONT_ID INT NOT NULL AUTO_INCREMENT,
    CAPTEUR_ID INT NOT NULL,
    LIBELLE_PONT VARCHAR(150),
    ADRESSE TEXT,
    PRIMARY KEY (PONT_ID),
    KEY FK_PONTS_PONTS_CAP_CAPTEURS (CAPTEUR_ID),
    CONSTRAINT FK_PONTS_PONTS_CAP_CAPTEURS FOREIGN KEY (CAPTEUR_ID)
         REFERENCES CAPTEURS(CAPTEUR_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE STATUS
CREATE TABLE STATUS (
    STATUS_ID INT NOT NULL,
    LIBELLE_STATUS TEXT,
    PRIMARY KEY (STATUS_ID)
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE TYPE_USER
CREATE TABLE TYPE_USER (
    TYPE_USER_ID INT NOT NULL,
    LIBELLE_TYPE_USER VARCHAR(50),
    PRIMARY KEY (TYPE_USER_ID)
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE USERS
CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    TYPE_USER_ID INT NOT NULL,
    USER_NAME VARCHAR(100),
    EMAIL VARCHAR(150),
    PASSWORD TEXT,
    CREATED_AT TIMESTAMP NULL DEFAULT NULL,
    LAST_SIGN TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (USER_ID),
    KEY USER_ET_TYPE_USER_FK (TYPE_USER_ID),
    CONSTRAINT FK_USERS_USER_ET_T_TYPE_USE FOREIGN KEY (TYPE_USER_ID)
         REFERENCES TYPE_USER(TYPE_USER_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE BATEAUX
CREATE TABLE BATEAUX (
    BATEAU_ID INT NOT NULL AUTO_INCREMENT,
    DIRECTION_CRENEAU_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    LIBELLE_BATEAU VARCHAR(100),
    IMMATRICULATION VARCHAR(100),
    HAUTEUR_MAX DECIMAL(10,2),
    CREATED_AT TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (BATEAU_ID),
    KEY ASSOCIATION_5_FK (DIRECTION_CRENEAU_ID),
    KEY BATEAUX_USER_FK (USER_ID),
    CONSTRAINT FK_BATEAUX_ASSOCIATI_DIRECTIO FOREIGN KEY (DIRECTION_CRENEAU_ID)
         REFERENCES DIRECTION_CRENEAU(DIRECTION_CRENEAU_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT,
    CONSTRAINT FK_BATEAUX_USER FOREIGN KEY (USER_ID)
         REFERENCES USERS(USER_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE HORAIRES_CRENEAUX
CREATE TABLE HORAIRES_CRENEAUX (
    HORAIRES_ID INT NOT NULL AUTO_INCREMENT,
    PERIODE_ID INT NOT NULL, 
    DIRECTION_CRENEAU_ID INT NOT NULL,
    HORAIRE_DEPART TIME NOT NULL, 
    HORAIRE_PASSAGE1 TIME, 
    HORAIRE_PASSAGE2 TIME,
    HORAIRE_PASSAGE3 TIME,
    PRIMARY KEY (HORAIRES_ID),
    CONSTRAINT FK_HORAIRES_PERIODE FOREIGN KEY (PERIODE_ID)
         REFERENCES PERIODE_CRENEAU(PERIODE_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT,
    CONSTRAINT FK_HORAIRES_DIRECTION FOREIGN KEY (DIRECTION_CRENEAU_ID)
         REFERENCES DIRECTION_CRENEAU(DIRECTION_CRENEAU_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION DE LA TABLE RESERVATION
CREATE TABLE RESERVATION (
    RESERVATION_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    PONT_ID INT NOT NULL,
    BATEAU_ID INT NOT NULL,
    STATUS_ID INT NOT NULL,
    HORAIRES_ID INT NOT NULL,
    DATE_RESERVATION TIMESTAMP NULL DEFAULT NULL,
    CAPACITE_MAX INT,
    PRIMARY KEY (RESERVATION_ID,USER_ID, PONT_ID, BATEAU_ID, STATUS_ID),
    KEY RESERVATION_FK (USER_ID),
    KEY RESERVATION2_FK (PONT_ID),
    KEY RESERVATION4_FK (BATEAU_ID),
    KEY RESERVATION5_FK (STATUS_ID),
    CONSTRAINT FK_RESERVAT_RESERVATI_USERS FOREIGN KEY (USER_ID)
         REFERENCES USERS(USER_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT,
    CONSTRAINT FK_RESERVAT_RESERVATI_PONTS FOREIGN KEY (PONT_ID)
         REFERENCES PONTS(PONT_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT,
    CONSTRAINT FK_RESERVAT_RESERVATI_BATEAUX FOREIGN KEY (BATEAU_ID)
         REFERENCES BATEAUX(BATEAU_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT,
    CONSTRAINT FK_RESERVAT_RESERVATI_STATUS FOREIGN KEY (STATUS_ID)
         REFERENCES STATUS(STATUS_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT,
    CONSTRAINT FK_RESERVAT_RESERVATI_HORAIRES FOREIGN KEY (HORAIRES_ID)
         REFERENCES HORAIRES_CRENEAUX(HORAIRES_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT
) ENGINE=InnoDB;

-- --------------------------------------------------------

-- CREATION TABLE POUR LES MESURES
CREATE TABLE MESURES_CAPTEURS (
    MESURE_ID INT NOT NULL AUTO_INCREMENT,
    CAPTEUR_ID INT NOT NULL,
    VALEUR DECIMAL(10,2),
    DATE_MESURE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MESURE_ID),
    INDEX IDX_CAPTEUR_DATE (CAPTEUR_ID, DATE_MESURE),
    CONSTRAINT FK_MESURES_CAPTEURS FOREIGN KEY (CAPTEUR_ID)
         REFERENCES CAPTEURS(CAPTEUR_ID)
         ON UPDATE RESTRICT
         ON DELETE RESTRICT
) ENGINE=InnoDB;

-- --------------------------------------------------------