-- DÉSACTIVER LES CONTRAINTES DE CLÉS ÉTRANGÈRES
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS MESURES_CAPTEURS;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS HORAIRES_CRENEAUX;
DROP TABLE IF EXISTS BATEAUX;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TYPE_USER;
DROP TABLE IF EXISTS PONTS;
DROP TABLE IF EXISTS STATUS;
DROP TABLE IF EXISTS CAPTEURS;
DROP TABLE IF EXISTS DIRECTION_CRENEAU;
DROP TABLE IF EXISTS PERIODE_CRENEAU;

-- RÉACTIVER LES CONTRAINTES DE CLÉS ÉTRANGÈRES
SET FOREIGN_KEY_CHECKS = 1;